using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace HollowSaint.FoundationKit
{
    /// <summary>
    /// Icons embedded in the DLL (HollowSaintMod/Icons/*.png, generated by
    /// tools/icons/make_icons.py), so new art needs a rebuild but no bundle rebuild.
    /// </summary>
    public static class KitIcons
    {
        private static readonly Dictionary<string, Texture2D> textures = new Dictionary<string, Texture2D>();
        private static readonly Dictionary<string, Sprite> sprites = new Dictionary<string, Sprite>();

        public static Texture2D Texture(string name)
        {
            Texture2D tex;
            if (textures.TryGetValue(name, out tex)) return tex;
            tex = null;
            var assembly = typeof(KitIcons).Assembly;
            using (var stream = assembly.GetManifestResourceStream("HollowSaint.Icons." + name + ".png"))
            {
                if (stream != null)
                {
                    var bytes = new byte[stream.Length];
                    int read = 0;
                    while (read < bytes.Length) read += stream.Read(bytes, read, bytes.Length - read);
                    tex = new Texture2D(2, 2, TextureFormat.RGBA32, true) { name = "HS_" + name, wrapMode = TextureWrapMode.Clamp };
                    if (!ImageConversion.LoadImage(tex, bytes, false)) tex = null;
                }
            }
            if (tex == null) Plugin.Log.LogWarning("HOLLOW_SAINT_ICON_MISSING " + name);
            textures[name] = tex;
            return tex;
        }

        public static Sprite Sprite(string name)
        {
            Sprite sprite;
            if (sprites.TryGetValue(name, out sprite)) return sprite;
            var tex = Texture(name);
            sprite = tex != null
                ? UnityEngine.Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height), new Vector2(0.5f, 0.5f), 100f)
                : null;
            if (sprite != null) sprite.name = "HS_" + name;
            sprites[name] = sprite;
            return sprite;
        }
    }
}
